db:
  image: 'postgres:13.1-alpine'
  volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  ports:
    - "5432:5432"
  container_name: db
  restart: always
  environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=mysecretpassword
